### ISSUE TITLE
Bot wont start, even after a valid Auth code is provided:

### ISSUE THREAD

**Issue by xoElf** [xMistt/fortnitepy-bot#196] opened 2020-12-04 01:56 UTC
I have tried entering a valid and invalid auth code, reinstalling py, reinstalling the packages, opening the bot on a different drive, adding all py locations to PATH, etc. I've basically tried every troubleshooting step and it wont go past this screen: 
![wont start](https://user-images.githubusercontent.com/75458737/101111803-f02a9600-35a9-11eb-9fd6-a1ddbe0d7208.PNG)
**Please help, im losing my mind.**

**Comment by Tommy3344** [comment] 2020-12-04 03:06
i will never understand how anyone gets this problem

**Comment by xoElf** [comment] 2020-12-04 20:27
> i will never understand how anyone gets this problem

there genuinely is no explanation as to why it happens

**Comment by xMistt** [comment] 2021-01-02 23:48
Duplicate of https://github.com/xMistt/fortnitepy-bot/issues/201. See solution there.

**Closed by xMistt** 2021-01-02 23:48 UTC
