### ISSUE TITLE
Doesn't Actually boot up.

### ISSUE THREAD

**Issue by Lesgosf** [xMistt/fortnitepy-bot#191] opened 2020-10-07 17:08 UTC
Whenever I boot up the bot it asks for the captcha, after I input the captcha it just freezes and does nothing.

**Comment by 0101001010** [comment] 2020-11-21 07:36
![опраок](https://user-images.githubusercontent.com/63189860/99870591-22c1af80-2bf6-11eb-9a50-0ea129307d62.PNG)
I have the same

**Comment by Tommy3344** [comment] 2020-11-22 05:43
wdym? how are you having problems? did you ever try to redownload the bot or reinstall packages because i never have this issue

**Comment by SimonBData** [comment] 2020-11-28 14:40
> ![опраок](https://user-images.githubusercontent.com/63189860/99870591-22c1af80-2bf6-11eb-9a50-0ea129307d62.PNG)
> У меня то же самое



> ![опраок](https://user-images.githubusercontent.com/63189860/99870591-22c1af80-2bf6-11eb-9a50-0ea129307d62.PNG)
> У меня то же самое



> ![опраок](https://user-images.githubusercontent.com/63189860/99870591-22c1af80-2bf6-11eb-9a50-0ea129307d62.PNG)
> I have the same

I also have this problem

**Comment by wavy0** [comment] 2020-11-29 10:04
bro, install packages, reinstal lthe bot, not that hard m8 and if that doesnt work then install the newest versions of the package and maybe run it on c:\ and not d:\ thank you

**Comment by Salty-Coder** [comment] 2020-12-29 16:16
I have the same issue, I reinstalled the packages but it still doesnt go any further than the Discord message...

**Comment by Tommy3344** [comment] 2020-12-29 16:43
Have you all made sure to download python 3.6? If so then try using 32x over 64x if you haven't already. (not sure if this would do anything but screw it)

**Comment by xMistt** [comment] 2021-01-02 23:51
> Have you all made sure to download python 3.6? If so then try using 32x over 64x if you haven't already. (not sure if this would do anything but screw it) **_Remember I dont have this problem so im not sure if this will help you_**

This would fix it but this is also a duplicate of https://github.com/xMistt/fortnitepy-bot/issues/201 which has another similar solution there.

**Closed by xMistt** 2021-01-02 23:51 UTC

**Comment by 0101001010** [comment] 2021-01-06 10:20
Thank you


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 3 янв. 2021 г. в 04:52, Oli <notifications@github.com>:
